### ISSUE TITLE
[Bug] Unable to generate micronaut app with JDK_16

### ISSUE THREAD

**Issue by JonathanGeoffroy** [tinesoft/nxrocks#135]
### Plugin Name

@nxrocks/nx-micronaut

### Plugin Version

1.0.2

### Nx Version

14.7.11

### Expected Behaviour

User should be able to generate a micronaut app with any suggested JDK

### Actual Behaviour

the generation crashes if user selects JDK_16 in the CLI :

```bash
>  NX   ❌ Error downloading Micronaut project zip from 'https://launch.micronaut.io'

   If the problem persists, please open an issue at https://github.com/tinesoft/nxrocks/issues, with the following information:
   ------------------------------------------------------
   Download URL: https://launch.micronaut.io/create/default/com.example.test?javaVersion=JDK_16&lang=JAVA&build=MAVEN&test=JUNIT&features=acme
   Response status: 400
   Response headers: {}
   ------------------------------------------------------
   Pass --verbose to see the stacktrace.
``` 

It's probably due to the fact micronaut generator doesn't offer JDK_16 anymore.

- https://launch.micronaut.io/create/default/com.example.test?javaVersion=JDK_16&lang=JAVA&build=MAVEN&test=JUNIT&features=acme with error `Failed to convert argument [javaVersion] for value [JDK_16] due to: No enum constant io.micronaut.starter.options.JdkVersion.JDK_16`
- Same URL but with `javaVersion=JDK_17` works fine

### Steps to reproduce the behaviour

1. Create a new app in a workspace
2. When CLI ask for java version, select JDK_16

**Comment by JonathanGeoffroy** [comment]
I'm reading some code and I think I'll be able to make a simple PR, i you don't mind. 

My concern on this particular issue is: should we still manually maintain a list of available JDK ? 
My guess is micronaut might drop another JDK in the future, in such case this bug will appears again.
Any suggestion on how we should address this ?

**Comment by tinesoft** [comment]
Hi @JonathanGeoffroy 

Thanks for reporting this issue.
I wasn't aware that using an obsolete JDK version would break the generator...

The list of JDKs presented during the generation is to provide convenience to the users during the process.
Having a "freetext" zone instead, will not be very user-friendly, and might lead to same issue if provided value does not match any supported JDK either...

The best solution would be to dynamically fetch and present only the list of availables JDKs (by an API call to launch.micronaut.io for e.g),
but unfortunately, this is not prossible (yet) because:

- no such API endpoint exists on launch.micronaut.io
-  Nx's generators (nor Angular 's schematics) support specifying a dynamic list of values

So for the time being, I will go with simply updating JDK16->JDK17
Hopefully, this kind of change does not happen that often...

**Comment by JonathanGeoffroy** [comment]
Hi @tinesoft, thanks for you reply and your suggestions.
The way you suggest this bug seems simple enough, I'll make a PR ASAP.

Thank you again :)
