### ISSUE TITLE
[Bug] Flutter doesn't generate with a project.json so none of the executors show up in the vscode plugin [Bug] 

### ISSUE THREAD

**Issue by algoflows** [tinesoft/nxrocks#159]
### Plugin Name

@nxrocks/nx-flutter

### Plugin Version

latest

### Nx Version

latest

### Expected Behaviour

an nx project.json should generate in the route of the flutter folder with the executors listed so that they show up in the nx vscode console plugin project bar

### Actual Behaviour

- no project.json
- no projects listed in the vscode nx console plugin
- no executors listed under the project in console plugin

### Steps to reproduce the behaviour

Generate a new flutter app

**Comment by tinesoft** [comment]
Hi @algoflows 

Thanks for using the plugin and for reporting this.
I think the issue was solved by this [commit](ffb0591cad36baef6afa68ccbcbe5418bdeb6086)


In the meantime, you can probably run the commands in a terminal (instead of via NxConsole)

```
npx nx g @nxrocks/nx-flutter:project
```

I'll notify back here, once the fix is released
