### ISSUE TITLE
A way to execute custom Gradle tasks

### ISSUE THREAD

**Issue by Edison-Hsu** [tinesoft/nxrocks#171]
### Is your feature request related to a problem? Please describe

Dear @nxrocks/nx-spring-boot maintainers,

I have encountered some issues while using your plugin to manage my Java Spring Boot projects. I am creating a custom Gradle task and want to execute it via the Nx workspace configuration. However, finding a direct method to achieve this functionality is challenging.

I attempted to add a new target in my `project.json` file, hoping to use the `@nxrocks/nx-spring-boot:gradle` executor to run my Gradle task. However, it seems that such an executor does not exist.

I have also considered using the `@nrwl/workspace:run-commands` executor and specifying a shell command to execute the Gradle task. However, this approach seems to introduce cross-platform compatibility issues, as different operating systems utilize different command line syntaxes.

I am wondering if there is a better way to execute custom Gradle tasks through the @nxrocks/nx-spring-boot plugin? If not, would you consider introducing such a feature?

I look forward to your response and greatly appreciate your assistance!

Best regards,

### Describe the idea you'd like

a better way to execute custom Gradle tasks

**Comment by tinesoft** [comment]
Hry @Edison-Hsu 

Thanks for using the plugin!

Regarding your question, first of all, there is no `@nxrocks/nx-spring-boot:gradle` executor.  What the plugin does out-of-the-box, is to define a [set of executors](https://github.com/tinesoft/nxrocks/tree/develop/packages/nx-spring-boot#plugin-usage) for **default tasks** that are available in a SpringBoot project managed by Gradle. 

Now, if you define  **custom gradle tasks** in your project,  you still can add them as target in your `project.json`.

And as you guess, you will have to use the generic [`nx:run-commands`](https://nx.dev/packages/nx/executors/run-commands#nx:run-commands)  executor to run the underlying task. 

Here is an example:

```
    "my-custom-target": {
      "executor": "nx:run-commands",
      "options": {
        "command": "./gradlew my-custom-task --argument-1",
        "cwd": "apps/path/to/my/project/root",
      }
    }
```

**Note**: 
- `nx:run-commands` is the new and shorter name  of  the `@nrwl/workspace:run-commands` executor, you can use one or the other , based on your version of Nx
- you have to set  the "cwd"  (current working directory) option of `nx:run-commands` executor, so that the `./gradlew` command (inside the project) is found 
- using `./gradlew` and `nx:run-commands` you shouldn't have to worry about  cross-platform compatibility issues,


Here is a [real-life example](https://github.com/Sage-Bionetworks/sage-monorepo/tree/main/apps/openchallenges/api-gateway)  of. project that uses `nxrocks/nx-spring-boot` with custom gradle targets.

Hope it helps
