### ISSUE TITLE
[Bug] Support for nx v17.x.x

### ISSUE THREAD

**Issue by manlyman29** [tinesoft/nxrocks#198]
### Plugin Name

@nxrocks/nx-flutter

### Nx Report

Apparently, nx-flutter still uses some removed/renamed APIs. More specifically you can see it calls for a non-existent fileutils.js
![Screenshot 2023-10-26 at 15 52 54](https://github.com/tinesoft/nxrocks/assets/63221039/aad75b4c-af02-4f9d-920a-628b67fc17c9)

### Expected Behaviour

nx would be able to function

### Actual Behaviour

nx daemon crashes

### Steps to reproduce the behavior

1-Create a project with nx 17.0.2
2-Add nx-flutter plugin
3-create a flutter project within the workspace.
4-try to run either the same project or any other project within the workspace. nx crashes and prompts to restart the nx daemon which doesn't resolve the problem. stack trace of the issue shows the problem is with the nx-flutter.

**Comment by tinesoft** [comment]
Hi @manlyman29 

Thanks for using the plugin...

Are you sure you are on the latest version of the plugin (nx-flutter@8.0.0)?

That is the version compatible with NX 17.x.x.


You can run `nx migrate @nxrocks/nx-flutter@latest`  to migrate .

**Comment by manlyman29** [comment]
Yes, i am using v8.0.0 of nx-flutter and just to be assured that I am on the right version I checked the package.json file of nx-flutter in node_modules and it shows 8.0.0 as the version.

It might be helpful that the trace for the error is in 
node_modules/@nxrocks/common/src/lib/core/jvm/utils.js

**Comment by manlyman29** [comment]
Many thanks!

**Comment by tinesoft** [comment]
Hi again,

Based on this issue, I did some cleanup in my internal dependencies in the PR #199 .
But I'm suspicious on the issue you had with `node_modules/@nxrocks/common/src/lib/core/jvm/utils.js` because that path is already no longer part of `@nxrocks/common`.... And I run nightly builds that haven't reported the issue either...

Could you try removing the node_modules, and re-run npm install ?

I suspect an outdated dependency somehow

**Comment by tinesoft** [comment]
Anyway, fixed by https://github.com/tinesoft/nxrocks/releases/tag/nx-flutter%2Fv8.0.1
