### ISSUE TITLE
[Feature] : support java 21

### ISSUE THREAD

**Issue by Fzum** [tinesoft/nxrocks#203]
### Is your feature request related to a problem? Please describe

as for now i think there is no support for java 21. would be nice to have that.

### Describe the idea you'd like

java 21 support

**Comment by tinesoft** [comment]
Hi @Fzum 

This repo holds 4 JVM-related related frameworks ( **Spring Boot** via `@nxrocks/nx-spring-boot`,  **Quarkus ** via `@nxrocks/nx-quarkus`,  **Micronaut ** via `@nxrocks/nx-micronaut` and  **Ktor ** via `@nxrocks/nx-ktor`).

What plugin do you want Java 21 support for ?
`@nxrocks/nx-spring-boot` already has it. The otherscan't yet because `Java 21` is not yet supported via their official starters.

**Comment by Fzum** [comment]
I wanted to have it for spring boot. I got an error using the nx console
when i tried to serve the application with java 21.

Tine Kondo ***@***.***> schrieb am Mo., 6. Nov. 2023, 10:25:

**Comment by tinesoft** [comment]
Hi @Fzum 

Can you provide more helpful information like:

- **Actual Stacktrace:**
- **Build System Used**: `Maven`, `Gradle` ?
- **Actual Java version**:  Output of `$ java -version`
- **OS**:
- **Command ran**: 
- etc

**Comment by Fzum** [comment]
im very sorry for the inconvenience i just figured out that my java_home env was not set correctly..

**Comment by tinesoft** [comment]
No worries!

Enjoy the plugin and don't hesitate to report issue or ask for features:-)


Also you can give the project a ⭐ to show your support ;-)
