### ISSUE TITLE
[Bug] create-nx-spring-boot fails to run

### ISSUE THREAD

**Issue by davidmccoy-8451** [tinesoft/nxrocks#211]
### Plugin Name

@nxrocks/nx-spring-boot

### Nx Report

When running `npx create-nx-spring-boot@latest`, after I enter an org name and select "yes" for using Nx wrapper and "No" for nx cloud, the command hangs and then fails. Using `--verbose`, I see the error

```
Error: Both project and target have to be specified
```

### Expected Behaviour

The creation completes.

### Actual Behaviour

The command fails to complete.

### Steps to reproduce the behaviour

Run `npx create-nx-spring-boot@latest`.

Fill in the first three steps of the workflow.

Get error.

**Comment by tinesoft** [comment]
Hi @davidmccoy-8451 

Thanks for using the package and for reporting the issue.
I'm already working on a fix. It should be released very soon.


Stay tuned

**Comment by m-jayson** [comment]
@tinesoft it also happens to me when I run `npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=container --parallel=2`

it hangs and failed.

![image](https://github.com/tinesoft/nxrocks/assets/21145779/2de7691d-e958-4a10-90e6-83afe527b410)

please advice thanks

**Comment by tinesoft** [comment]
Hi @davidmccoy-8451 

Some updates:

I have updated my code to be compatible with latest changes in Nx, but the root cause of the issue, seems to be a bug in Nx itself, with the `nx init` command.  Here is the related ticket for ref: https://github.com/nrwl/nx/issues/21786

Once solved by Nx team,  you should be able to create the Nx Spring Boot workspace just fine.
