### ISSUE TITLE
[Bug] [nx-flutter] TypeError: options.platforms.join is not a function

### ISSUE THREAD

**Issue by scarnett** [tinesoft/nxrocks#22]
Plugin Name and Version:
nx-flutter@1.1.0

Nx Version (`nx --version`):
11.1.1

Angular CLI version (`ng --version`):
11.1.1

#### Expected Behaviour
The application should be created

#### Actual Behaviour
errors out with `TypeError: options.platforms.join is not a function`

#### Steps to reproduce the behaviour
`nx g @nxrocks/nx-flutter:app test`

? What package name would you like to use? `com.test`
? What is the project about? `test`
? Which Android language would you like to use? `Kotlin`
? Which iOS language would you like to use? `Swift`
? Which type of Flutter project would you like to create? `Flutter application`
? Which platforms would you like to use (--template must have been set to 'app' or 'plugin') ? `Android platform`
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (4 weeks ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4
TypeError: options.platforms.join is not a function
    at Object.buildFlutterCreateOptions (/home/scott/dev/apps/test/foo/node_modules/@nxrocks/nx-flutter/src/utils/flutter-utils.js:25:74)

Thanks!

**Comment by scarnett** [comment]
I now receive a different error after this update:

`Property 'platforms' does not match the schema. 'android' should be a 'array'.`

Same steps as above.

**Comment by tinesoft** [comment]
Hi @scarnett,

Thanks again for the feedback.

This seems to be due to a bug in Nx itself (with the `nx generate` command).
I have reported the issue on Nx repo:  https://github.com/nrwl/nx/issues/4499

In the meantime, a workaround would be to run the generator with `Angular DevKit's schematics cli` instead of Nx's.

`$ npx @angular-devkit/schematics-cli @nxrocks/nx-flutter:app flutter-app`

(_you may need to temporary change the `"version"` field in your `workspace.json` file from `"2"` to `"1"`, otherwise you'll get this: `"Error: Invalid format version detected - Expected:[ 1 ] Found: [ 2 ]" `. Once the generation is successful, you can change it back to "2" again_).


I'm monitoring the issue on Nx, and will provide a more appropriate solution once they do.

**Comment by scarnett** [comment]
Your workaround worked great for me. Thanks for your help @tinesoft!
